### ISSUE TITLE
DOOR_ACCOUNT_SEED env variable description is incorrect

### ISSUE THREAD

**Issue by SFsourDoh** [xpring-eng/sidechain-launch-kit#47]
The DOOR_ACCOUNT_SEED env variable description starts with the websocket port text

**The public Websocket port of the mainchain node.** Either set the environment variable DOOR_ACCOUNT_SEED (in your system or in the .env file) or use the command line switch --door_seed. This is used in the script that creates the config files.

**Comment by mvadari** [comment]
Thanks for catching that!
